apiVersion: apps/v1
kind: Deployment
metadata:
   name: devops-app
spec:
   replicas: {{ .Values.replicaCount }}
   selector:
      matchLabels:
        app: devops-app
   template:
      metadata:
        labels:
          app: devops-app	    
      spec:
        containers:
          - name: devops-app
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
              - containerPort: 8080
            envFrom:
              - configMapRef:
                  name: devops-app-config
              - secretRef:
                  name: devops-app-secret
            volumeMounts:
              - name: app-storage
                mountPath: /data
            resources:
              requests:
                cpu: "100m"
              limits:
                cpu: "500m"
            readinessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 20
        volumes:
          - name: app-storage
            persistentVolumeClaim:
              claimName: devops-app-pvc