apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
spec:
  type: ClusterIP
  selector:
    app: devops-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}