---
# Source: devops-app/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
   name: devops-app-secret
type: Opaque
stringData:
   USERNAME: "demo-user"
   PASSWORD: "change-me"

---
# Source: devops-app/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap

metadata:
   name: devops-app-config
data:
   APP_ENV: "manual"
   APP_MESSAGE: "Manual deployment on Amazon EKS"

---
# Source: devops-app/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
---
# Source: devops-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
spec:
  type: ClusterIP
  selector:
    app: devops-app
  ports:
    - port: 80
      targetPort: 8080
---
# Source: devops-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
   name: devops-app
spec:
   replicas: 2
   selector:
      matchLabels:
        app: devops-app
   template:
      metadata:
        labels:
          app: devops-app	    
      spec:
        containers:
          - name: devops-app
            image: "808935753983.dkr.ecr.us-east-1.amazonaws.com/devops-final-app:test"
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8080
            envFrom:
              - configMapRef:
                  name: devops-app-config
              - secretRef:
                  name: devops-app-secret
            volumeMounts:
              - name: app-storage
                mountPath: /data
            resources:
              requests:
                cpu: "100m"
              limits:
                cpu: "500m"
            readinessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 20
        volumes:
          - name: app-storage
            persistentVolumeClaim:
              claimName: devops-app-pvc
---
# Source: devops-app/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
# Source: devops-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-app-ingress
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-app-service
                port:
                  number: 80
---
# Source: devops-app/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "devops-app-test-connection"
  labels:
    helm.sh/chart: devops-app-0.1.0
    app.kubernetes.io/name: devops-app
    app.kubernetes.io/instance: devops-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['devops-app:80']
  restartPolicy: Never

