replicaCount: 2
image:
   repository: 808935753983.dkr.ecr.us-east-1.amazonaws.com/devops-final-app
   tag: "test"
   pullPolicy: IfNotPresent

service:
   port: 80
   targetPort: 8080

app:
   environment: manual
   message: "Manual deployment on Amazon EKS"

secret:
   username: demo-user
   password: change-me

persistence:
   enabled: true
   storageClass: gp3-csi
   size: 1Gi

ingress:
   enabled: true
   className: alb

hpa:
   enabled: true
   minReplicas: 2
   maxReplicas: 5
   cpu: 60
